#property.basePath=test-output/Logs
#
#
#
##Define the file Appender
#appender.file.type=File
#appender.file.name=fileAppender
#appender.file.filename=${basePath}/log_${date:yyyy-MM-dd-HH-mm-ss}.log
#appender.file.layout.type=PatternLayout
#appender.file.layout.disableAnsi=false
#appender.file.filter.threshold.level=info
#appender.file.layout.pattern=[%p] - [%d{dd-MM-yyyy HH:mm:ss}] [%t] [%c] - %msg%n
#
#
##Define the stdout
#appender.stdout.type=File
#appender.stdout.name=consoleAppender
#appender.stdout.filename=${basePath}/log_${date:yyyy-MM-dd-HH-mm-ss}.log
#appender.stdout.layout.type=PatternLayout
#appender.stdout.layout.disableAnsi=false
#appender.stdout.filter.threshold.type=ThresholdFilter
#appender.stdout.filter.threshold.level=info
#appender.stdout.layout.pattern=%highlight{[%p] - [%d{dd-MM-yyyy HH:mm:ss}] [%t] [%c] - %msg%n}{FATAL=red blink, ERROR=red, WARN=yellow bold, INFO=green, DEBUG=blue, TRACE=black}
##Define the root logger
#rootLogger.level=debug, consoleAppender, fileAppender
#rootLogger=debug

property.basePath = test-output/Logs

# ============ Filters ============
filters = threshold
filter.threshold.type = ThresholdFilter
filter.threshold.level = info

# ============ File Appender ============
appender.file.type = File
appender.file.name = fileAppender
appender.file.filename = ${basePath}/log_${date:yyyy-MM-dd-HH-mm-ss}.log
appender.file.layout.type = PatternLayout
appender.file.layout.disableAnsi = false
appender.file.layout.pattern = [%p] - [%d{dd-MM-yyyy HH:mm:ss}] [%t] [%c] - %msg%n

# ============ Console Appender ============
appender.console.type = Console
appender.console.name = consoleAppender
appender.console.layout.type = PatternLayout
appender.console.layout.disableAnsi = false
appender.console.filter.threshold.type = ThresholdFilter
appender.console.filter.threshold.level = info
appender.console.layout.pattern = %highlight{[%p] - [%d{dd-MM-yyyy HH:mm:ss}] [%t] [%c] - %msg%n}{FATAL=red blink, ERROR=red, WARN=yellow bold, INFO=green, DEBUG=blue, TRACE=black}

# ============ Root Logger ============
rootLogger.level = debug
rootLogger.appenderRefs = consoleAppender, fileAppender
rootLogger.appenderRef.consoleAppender.ref = consoleAppender
rootLogger.appenderRef.fileAppender.ref = fileAppender

